server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: security-ms
          uri: ${ROUTE_SECURITY_MS:lb://security-ms}
          predicates:
            - Path=/auth/v1/**
          filters:
            - RewritePath=/auth/v1/?(?<path>.*), /$\{path}
        - id: storage-ms
          uri: ${ROUTE_STORAGE_MS:lb://storage-ms}
          predicates:
            - Path=/storage/v1/**
          filters:
            - RewritePath=/storage/v1/?(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLE:true}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://host.docker.internal:8761/eureka/}
    renewal-interval-in-seconds: ${EUREKA_CLIENT_HEARTBEAT:30}
    instance-info-replication-interval-seconds: ${EUREKA_CLIENT_INSTANCE_REPLICATION_INTERVAL:60}
    lease-expiration-duration-in-seconds: ${EUREKA_CLIENT_LEASE_EXPIRATION_DURATION:90}
jwt:
  secret: ${JWT_SECRET:-r0M7GqBT5VAmx2871SJN88g7fdOpVIOh}
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSURE}
  endpoint:
    env:
      show-values: ${ACTUATOR_SHOW_ENV}
springdoc:
  cache:
    disabled: true
